name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: '🚀 New features'
    labels:
      - 'enhancement'
  - title: '🐛 Bugs fixes'
    labels:
      - 'bug'
  - title: '📕 Documentation'
    labels:
      - 'type:documentation'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## What`s changed
  $CHANGES
