name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: '🚀 New features'
    labels:
      - 'enhancement'
  - title: '🐛 Bugs fixes'
    labels:
      - 'bug'
  - title: '🤖 CI/CD'
    labels:
      - 'ci'
  - title: '📕 Documentation'
    labels:
      - 'documentation'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## ❓ Unlabelled changes
  $CHANGES
