# Статьи
# 1. Пример YAML файла: https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions#create-an-example-workflow
# 2. Инструкцию по развертыванию CI/CD: https://habr.com/ru/company/jugru/blog/505994/
# 3. Сборка Unity-проекта: https://game.ci/docs/github/getting-started
name: build-app
on: [pull_request, push]
jobs:
  build-app:
    # Доступные окружения: https://github.com/actions/virtual-environments#available-environments
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
      # Справочник по аргументам unity.exe: https://docs.unity3d.com/Manual/CommandLineArguments.html
      # Пример сборки проекта на Unity: https://habr.com/ru/post/479884/
      # - run: unity -batchmode -quit -projectPath ./ -executeMethod BuildEntryPoint.BuildWindowsVersion -buildTarget Win -logFile "$LOGS_PATH/build-app.log"

      - name: Build application
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: WebGL
