# Использованные источники
# - Документация GitHub Actions: https://docs.github.com/en/actions/learn-github-actions/
# - Доступные окружения для Runner-ов GitHub Actions: https://github.com/actions/virtual-environments#available-environments
# - Action-ы для сборки проектов на Unity: https://game.ci/docs/github/getting-started
# - Справочник по аргументам Unity.exe: https://docs.unity3d.com/Manual/CommandLineArguments.html
# - Инструкцию по развертыванию CI/CD: https://habr.com/ru/company/jugru/blog/505994/

name: Build Application
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Caching Library
        uses: actions/cache@v2
        with:
          path: Library
          key: Library

      - name: Build Application
        uses: game-ci/unity-builder@v2.0-alpha-10
        env:
          # TODO: положить лицензию в secrets
          UNITY_LICENSE_FILE: ./Licenses/Unity_v2020.x.ulf
        with:
          targetPlatform: WebGL
          unityVersion: 2020.3.9f1
          buildsPath: Build

      - name: Output Application
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: Build
