# Статьи
# 1. Пример YAML файла: https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions#create-an-example-workflow
# 2. Инструкцию по развертыванию CI/CD: https://habr.com/ru/company/jugru/blog/505994/
# 3. Сборка Unity-проекта: https://game.ci/docs/github/getting-started
# 4. Доступные окружения: https://github.com/actions/virtual-environments#available-environments
# 5. Справочник по аргументам unity.exe: https://docs.unity3d.com/Manual/CommandLineArguments.html
# 6. Пример сборки проекта на Unity: https://habr.com/ru/post/479884/

name: Build Application
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Caching Library
        uses: actions/cache@v2
        with:
          path: Library
          key: Library

      - name: Build Application
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: '<?xml version="1.0" encoding="UTF-8"?><root>
    <License id="Terms">
        <MachineBindings>
            <Binding Key="1" Value="576562626572264761624c65526f7578"/>
            <Binding Key="2" Value="576562626572264761624c65526f7578"/>
        </MachineBindings>
        <MachineID Value="D7nTUnjNAmtsUMcnoyrqkgIbYdM="/>
        <SerialHash Value="be86ac06b3ed13dbd01c015e9bf5f40329fc1ca7"/>
        <Features>
            <Feature Value="33"/>
            <Feature Value="1"/>
            <Feature Value="12"/>
            <Feature Value="2"/>
            <Feature Value="24"/>
            <Feature Value="3"/>
            <Feature Value="36"/>
            <Feature Value="17"/>
            <Feature Value="19"/>
            <Feature Value="62"/>
        </Features>
        <DeveloperData Value="AQAAAEY0LUVEUFUtOVFGTS1DWFdDLVNLUkUtQUtQTg=="/>
        <SerialMasked Value="F4-EDPU-9QFM-CXWC-SKRE-XXXX"/>
        <StartDate Value="2021-05-24T00:00:00"/>
        <UpdateDate Value="2021-05-25T19:09:17"/>
        <InitialActivationDate Value="2021-05-24T16:14:05"/>
        <LicenseVersion Value="6.x"/>
        <ClientProvidedVersion Value="2019.3.11f1"/>
        <AlwaysOnline Value="false"/>
        <Entitlements>
            <Entitlement Ns="unity_editor" Tag="UnityPersonal" Type="EDITOR" ValidTo="9999-12-31T00:00:00"/>
            <Entitlement Ns="unity_editor" Tag="DarkSkin" Type="EDITOR_FEATURE" ValidTo="9999-12-31T00:00:00"/>
        </Entitlements>
    </License>
<Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments"/><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><Reference URI="#Terms"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><DigestValue>Qqhu/i98ZwnW+0YDU0x+70kdRxA=</DigestValue></Reference></SignedInfo><SignatureValue>Lhj1VHqogrLXLcFI8i6lt+cViXSvbEPTNIROJVRk/K0nh5mawn3GJZeAXYcgUAqPSqXprrbNLjrd
1TL6ar5dJhvZgBbcxbrTb7JYxGf7RCtqYd9lpuDCSk1bnDcUa8LFv+y/YRXHBHpEa+YMhJSKqG+J
HC+JK5MnUzJKKgnAGEhckv1MoxBWXvMIIIg/T6U6CjAmKlvWoSjrEJcxPZ4nalzBopCZQGaaU9Qb
4+uGKwInI3AjDc2Sj9wJTQPE2a001SSiRACf8sDvsDJQd+Y7s3lwyiT5JSumyuT9CID/oeoseZr1
1u1oXItQM0F4VnWUhUIVyMgvHWOap3a4GidQUA==</SignatureValue></Signature></root>'
        with:
          targetPlatform: StandaloneWindows
          unityVersion: 2019.3.11f1
          buildsPath: Build

      - name: Output Application
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: Build
