# Использованные источники
# - Документация GitHub Actions: https://docs.github.com/en/actions/learn-github-actions/
# - Доступные окружения для Runner-ов GitHub Actions: https://github.com/actions/virtual-environments#available-environments
# - Action-ы для сборки проектов на Unity: https://game.ci/docs/github/getting-started
# - Справочник по аргументам Unity.exe: https://docs.unity3d.com/Manual/CommandLineArguments.html
# - Инструкцию по развертыванию CI/CD: https://habr.com/ru/company/jugru/blog/505994/

name: Release Application
on:
  push:
    branches:
      - master
jobs:
  build-application:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/checkout-repository
      - uses: ./.github/actions/cache-building
      - uses: ./.github/actions/build-application
      - uses: ./.github/actions/output-application

  create-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/create-draft
      - uses: ./.github/actions/output-application
