# https://habr.com/ru/company/jugru/blog/505994/

name: Create Draft Release
on:
  push:
    branches:
      - master
jobs:
  release-draft:
    runs-on: ubuntu-latest
    steps:
      
      - name: Create Draft Release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
